# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('input_csv_fields', jsonfield.fields.JSONField()),
                ('answers', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HitBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HitTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('form', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='hitbatch',
            name='hit_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.HitTemplate'),
        ),
        migrations.AddField(
            model_name='hit',
            name='hit_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.HitBatch'),
        ),
    ]
