# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='hitassignment',
            options={'verbose_name': 'Task Assignment'},
        ),
        migrations.AlterModelOptions(
            name='hitbatch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='hitproject',
            options={'verbose_name': 'Project'},
        ),
        migrations.AlterField(
            model_name='hitbatch',
            name='assignments_per_hit',
            field=models.IntegerField(default=1, verbose_name=b'Assignments per Task'),
        ),
    ]
