# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitbatch',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hittemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
