# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 17:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hittemplate',
            name='fieldnames',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
