# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitassignment',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hitbatch',
            name='allotted_assignment_time',
            field=models.IntegerField(default=24),
        ),
    ]
