# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0003_auto_20181004_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitassignment',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hitbatch',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hitproject',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hitproject',
            name='assignments_per_hit',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='hitproject',
            name='login_required',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
