# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0003_hittemplate_login_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hittemplate',
            name='filename',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
