# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0005_hittemplate_form_has_submit_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitassignment',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
