# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0006_hitassignment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitbatch',
            name='allotted_assignment_time',
            field=models.IntegerField(default=24),
        ),
    ]
