FROM python:3.10-slim-bullseye
LABEL org.opencontainers.image.title="Turkle SQLite Image" \
      org.opencontainers.image.description="Image for running a Turkle instance using SQLite" \
      org.opencontainers.image.authors="Cash Costello <cash.costello@gmail.com>" \
      org.opencontainers.image.licenses="BSD-2-Clause"

RUN apt-get update && apt-get install -y --no-install-recommends \
    cron \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/turkle

COPY requirements.txt /opt/turkle/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt gunicorn whitenoise

COPY turkle /opt/turkle/turkle
COPY manage.py /opt/turkle/manage.py
COPY turkle_site /opt/turkle/turkle_site
COPY docker/resources/create_turkle_admin.sh /opt/turkle/create_turkle_admin.sh
COPY docker/resources/entrypoint.sh /usr/local/bin/entrypoint.sh

COPY docker/resources/turkle.crontab /etc/cron.d/turkle
RUN crontab /etc/cron.d/turkle

ENV TURKLE_DOCKER=1
ENV TURKLE_DATABASE_BACKEND=SQLite

RUN python manage.py collectstatic
RUN python manage.py migrate
RUN ./create_turkle_admin.sh

VOLUME /opt/turkle

EXPOSE 8080

CMD [ "/usr/local/bin/entrypoint.sh" ]
