FROM python:3.10-slim-bullseye
MAINTAINER Cash Costello <cash.costello@gmail.com>
LABEL Description="Image for running a Turkle interface using MySQL"

WORKDIR /opt/turkle
COPY requirements.txt /opt/turkle/requirements.txt

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends cron default-libmysqlclient-dev build-essential pkg-config; \
    pip install --no-cache-dir --upgrade -r requirements.txt gunicorn mysqlclient whitenoise; \
    apt-get remove --purge -y build-essential; \
    apt-get autoremove -y; \
    rm -rf /var/lib/apt/lists/*

COPY docker/resources/wait-for-it.sh docker/resources/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-it.sh /usr/local/bin/entrypoint.sh

COPY docker/resources/turkle.crontab /etc/cron.d/turkle
RUN chmod 0644 /etc/cron.d/turkle && crontab /etc/cron.d/turkle

COPY turkle /opt/turkle/turkle
COPY manage.py /opt/turkle/manage.py
COPY turkle_site /opt/turkle/turkle_site

ENV TURKLE_DOCKER=1
ENV TURKLE_DATABASE_BACKEND=MySQL

RUN python manage.py collectstatic

VOLUME /opt/turkle

EXPOSE 8080

CMD [ "/usr/local/bin/entrypoint.sh" ]
