# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sd_services.document_management import access_tokens_pb2 as sd__services_dot_document__management_dot_access__tokens__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sd_services/document_management/access_tokens_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccessTokensStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccessToken = channel.unary_unary(
                '/document_management.AccessTokens/CreateAccessToken',
                request_serializer=sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenResponse.FromString,
                _registered_method=True)


class AccessTokensServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessTokensServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccessToken,
                    request_deserializer=sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document_management.AccessTokens', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document_management.AccessTokens', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessTokens(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.AccessTokens/CreateAccessToken',
            sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenRequest.SerializeToString,
            sd__services_dot_document__management_dot_access__tokens__pb2.AccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
