# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sd-services/document_management/access_tokens.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sd-services/document_management/access_tokens.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3sd-services/document_management/access_tokens.proto\x12\x13\x64ocument_management\"\xfa\x02\n\x12\x41\x63\x63\x65ssTokenRequest\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x34\n\x0bsource_type\x18\x02 \x01(\x0e\x32\x1f.document_management.SourceType\x12R\n\x11permitted_actions\x18\x03 \x03(\x0e\x32\x37.document_management.AccessTokenRequest.PermittedAction\x12\x15\n\rdocument_type\x18\x04 \x01(\t\x12\x1e\n\x16whitelisted_mime_types\x18\x05 \x03(\t\x12\x1d\n\x15\x63ombined_document_ids\x18\x06 \x03(\x05\x12\x13\n\x0b\x64ocument_id\x18\x07 \x01(\t\x12\x0f\n\x07s3_path\x18\x08 \x01(\t\"K\n\x0fPermittedAction\x12\x08\n\x04SHOW\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\x0b\n\x07\x44\x45STROY\x10\x02\x12\t\n\x05INDEX\x10\x03\x12\n\n\x06RENAME\x10\x04\"+\n\x13\x41\x63\x63\x65ssTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t*\xc7\x02\n\nSourceType\x12\x0c\n\x08\x43LOSINGS\x10\x00\x12\n\n\x06ORDERS\x10\x01\x12\x0c\n\x08PACKAGES\x10\x02\x12\n\n\x06\x45NOTES\x10\x03\x12\x11\n\rPOST_CLOSINGS\x10\x04\x12\x15\n\x11SETTLEMENT_ORDERS\x10\x05\x12\x14\n\x10\x43LOSINGS_REDRAWS\x10\x06\x12\x19\n\x15\x43LOSINGS_CLOSINGUSERS\x10\x07\x12\n\n\x06\x45MAILS\x10\x08\x12\x1f\n\x1b\x43LOSINGS_DOCUMENT_PUSHBACKS\x10\t\x12\x11\n\rPACKAGE_PAGES\x10\n\x12\x19\n\x15\x43LOSINGS_DATA_EXPORTS\x10\x0b\x12\x17\n\x13\x43LOSING_DISCLOSURES\x10\x0c\x12\x1c\n\x18\x43LOSING_DISCLOSURE_PAGES\x10\r\x12\x0f\n\x0b\x45NOTE_PAGES\x10\x0e\x12\x07\n\x03LOS\x10\x0f\x32x\n\x0c\x41\x63\x63\x65ssTokens\x12h\n\x11\x43reateAccessToken\x12\'.document_management.AccessTokenRequest\x1a(.document_management.AccessTokenResponse\"\x00\x42\x35Z3github.com/snapdocs/go-services/document_managementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sd_services.document_management.access_tokens_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/snapdocs/go-services/document_management'
  _globals['_SOURCETYPE']._serialized_start=503
  _globals['_SOURCETYPE']._serialized_end=830
  _globals['_ACCESSTOKENREQUEST']._serialized_start=77
  _globals['_ACCESSTOKENREQUEST']._serialized_end=455
  _globals['_ACCESSTOKENREQUEST_PERMITTEDACTION']._serialized_start=380
  _globals['_ACCESSTOKENREQUEST_PERMITTEDACTION']._serialized_end=455
  _globals['_ACCESSTOKENRESPONSE']._serialized_start=457
  _globals['_ACCESSTOKENRESPONSE']._serialized_end=500
  _globals['_ACCESSTOKENS']._serialized_start=832
  _globals['_ACCESSTOKENS']._serialized_end=952
# @@protoc_insertion_point(module_scope)
