# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from sd_services.document_management import documents_pb2 as sd__services_dot_document__management_dot_documents__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sd_services/document_management/documents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDocuments = channel.unary_unary(
                '/document_management.Documents/ListDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocuments = channel.unary_unary(
                '/document_management.Documents/GetDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentsRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentsResponse.FromString,
                _registered_method=True)
        self.CreateDocument = channel.unary_unary(
                '/document_management.Documents/CreateDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.RenameDocument = channel.unary_unary(
                '/document_management.Documents/RenameDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.RenameDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.RenameDocumentResponse.FromString,
                _registered_method=True)
        self.UploadDocument = channel.stream_unary(
                '/document_management.Documents/UploadDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.UploadDocumentChunk.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CombineDocuments = channel.unary_unary(
                '/document_management.Documents/CombineDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CombineDocumentsByIds = channel.unary_unary(
                '/document_management.Documents/CombineDocumentsByIds',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsByIdsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SplitDocument = channel.unary_unary(
                '/document_management.Documents/SplitDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.SplitDocumentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_stream(
                '/document_management.Documents/GetDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentResponseChunk.FromString,
                _registered_method=True)
        self.GetDocumentMetadata = channel.unary_unary(
                '/document_management.Documents/GetDocumentMetadata',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentMetadataResponse.FromString,
                _registered_method=True)
        self.DestroyDocuments = channel.unary_unary(
                '/document_management.Documents/DestroyDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DestroyDocument = channel.unary_unary(
                '/document_management.Documents/DestroyDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetOriginalDocumentIds = channel.unary_unary(
                '/document_management.Documents/GetOriginalDocumentIds',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsResponse.FromString,
                _registered_method=True)
        self.GetPresignedUploadUrl = channel.unary_unary(
                '/document_management.Documents/GetPresignedUploadUrl',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlResponse.FromString,
                _registered_method=True)
        self.RecombineDocuments = channel.unary_unary(
                '/document_management.Documents/RecombineDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.RecombineDocumentsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CopyDocument = channel.unary_unary(
                '/document_management.Documents/CopyDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.CopyDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.CopyDocumentResponse.FromString,
                _registered_method=True)
        self.TransferDocuments = channel.unary_unary(
                '/document_management.Documents/TransferDocuments',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsResponse.FromString,
                _registered_method=True)
        self.ArchiveDocument = channel.unary_unary(
                '/document_management.Documents/ArchiveDocument',
                request_serializer=sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentRequest.SerializeToString,
                response_deserializer=sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentResponse.FromString,
                _registered_method=True)


class DocumentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocuments(self, request, context):
        """Gets the document metadata for a list of document ids
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request_iterator, context):
        """Upload a document in chunks. DEPRECATED: Use GetPresignedUploadUrl and CreateDocument instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CombineDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CombineDocumentsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Get document contents. DEPRECATED: Use GetDocuments and download the file from the remote_url instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentMetadata(self, request, context):
        """Get document metadata. DEPRECATED: Use GetDocuments instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOriginalDocumentIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresignedUploadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecombineDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferDocuments(self, request, context):
        """Transfers documents to a new source type/id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveDocument(self, request, context):
        """Archive a document by copying it to a new bucket
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.ListDocumentsRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'GetDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentsRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentsResponse.SerializeToString,
            ),
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.CreateDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'RenameDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.RenameDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.RenameDocumentResponse.SerializeToString,
            ),
            'UploadDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.UploadDocumentChunk.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CombineDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.CombineDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CombineDocumentsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.CombineDocumentsByIds,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsByIdsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SplitDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.SplitDocumentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentResponseChunk.SerializeToString,
            ),
            'GetDocumentMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentMetadata,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.GetDocumentMetadataResponse.SerializeToString,
            ),
            'DestroyDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DestroyDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetOriginalDocumentIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOriginalDocumentIds,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsResponse.SerializeToString,
            ),
            'GetPresignedUploadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresignedUploadUrl,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlResponse.SerializeToString,
            ),
            'RecombineDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.RecombineDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.RecombineDocumentsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CopyDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.CopyDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.CopyDocumentResponse.SerializeToString,
            ),
            'TransferDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferDocuments,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsResponse.SerializeToString,
            ),
            'ArchiveDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveDocument,
                    request_deserializer=sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentRequest.FromString,
                    response_serializer=sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document_management.Documents', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document_management.Documents', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Documents(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/ListDocuments',
            sd__services_dot_document__management_dot_documents__pb2.ListDocumentsRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/GetDocuments',
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentsRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/CreateDocument',
            sd__services_dot_document__management_dot_documents__pb2.CreateDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/RenameDocument',
            sd__services_dot_document__management_dot_documents__pb2.RenameDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.RenameDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/document_management.Documents/UploadDocument',
            sd__services_dot_document__management_dot_documents__pb2.UploadDocumentChunk.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CombineDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/CombineDocuments',
            sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CombineDocumentsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/CombineDocumentsByIds',
            sd__services_dot_document__management_dot_documents__pb2.CombineDocumentsByIdsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/SplitDocument',
            sd__services_dot_document__management_dot_documents__pb2.SplitDocumentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/document_management.Documents/GetDocument',
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/GetDocumentMetadata',
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.GetDocumentMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/DestroyDocuments',
            sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/DestroyDocument',
            sd__services_dot_document__management_dot_documents__pb2.DestroyDocumentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOriginalDocumentIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/GetOriginalDocumentIds',
            sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.GetOriginalDocumentIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresignedUploadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/GetPresignedUploadUrl',
            sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.GetPresignedUploadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecombineDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/RecombineDocuments',
            sd__services_dot_document__management_dot_documents__pb2.RecombineDocumentsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/CopyDocument',
            sd__services_dot_document__management_dot_documents__pb2.CopyDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.CopyDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/TransferDocuments',
            sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.TransferDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document_management.Documents/ArchiveDocument',
            sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentRequest.SerializeToString,
            sd__services_dot_document__management_dot_documents__pb2.ArchiveDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
