# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sd-services/document_management/events.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sd-services/document_management/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sd_services.document_management import access_tokens_pb2 as sd__services_dot_document__management_dot_access__tokens__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sd-services/document_management/events.proto\x12\x13\x64ocument_management\x1a\x33sd-services/document_management/access_tokens.proto\"\xd6\x02\n\rDocumentEvent\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x34\n\x0bsource_type\x18\x02 \x01(\x0e\x32\x1f.document_management.SourceType\x12\x15\n\rdocument_type\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x1c\n\x14generated_by_user_id\x18\x05 \x01(\x05\x12\x1e\n\x16generated_by_user_role\x18\x06 \x01(\t\x12\x10\n\x08\x66ilename\x18\x07 \x01(\t\x12\x35\n\x07request\x18\x08 \x01(\x0b\x32$.document_management.UserHttpRequest\x12\x37\n\x06\x61\x63tion\x18\t \x01(\x0e\x32\'.document_management.DocumentActionType\x12\x19\n\x11previous_filename\x18\n \x01(\t\"_\n\x0fUserHttpRequest\x12\x11\n\tremote_ip\x18\x01 \x01(\t\x12\x12\n\nuser_agent\x18\x02 \x01(\t\x12\x14\n\x0coriginal_url\x18\x03 \x01(\t\x12\x0f\n\x07referer\x18\x04 \x01(\t*K\n\x12\x44ocumentActionType\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0e\n\nDOWNLOADED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\x0b\n\x07RENAMED\x10\x03\x42\x35Z3github.com/snapdocs/go-services/document_managementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sd_services.document_management.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/snapdocs/go-services/document_management'
  _globals['_DOCUMENTACTIONTYPE']._serialized_start=564
  _globals['_DOCUMENTACTIONTYPE']._serialized_end=639
  _globals['_DOCUMENTEVENT']._serialized_start=123
  _globals['_DOCUMENTEVENT']._serialized_end=465
  _globals['_USERHTTPREQUEST']._serialized_start=467
  _globals['_USERHTTPREQUEST']._serialized_end=562
# @@protoc_insertion_point(module_scope)
