# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('allotted_assignment_time', models.IntegerField(default=24)),
                ('assignments_per_hit', models.IntegerField(default=1, verbose_name=b'Assignments per Task')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('input_csv_fields', jsonfield.fields.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.Batch')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='HitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField(blank=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.Hit')),
            ],
            options={
                'verbose_name': 'Task Assignment',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('assignments_per_hit', models.IntegerField(db_index=True, default=1)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=1024)),
                ('html_template', models.TextField()),
                ('html_template_has_submit_button', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=1024)),
                ('fieldnames', jsonfield.fields.JSONField(blank=True)),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkle.Project'),
        ),
    ]
