# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_work_on', 'Can work on Tasks for this Project'),), 'verbose_name': 'Project'},
        ),
        migrations.AddField(
            model_name='project',
            name='custom_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
