# Generated by Django 2.2.19 on 2021-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0009_batch_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'permissions': (('can_work_on', 'Can work on Tasks for this Project'),), 'verbose_name': 'Project'},
        ),
        migrations.AddField(
            model_name='project',
            name='demonstrate_broken_migrations',
            field=models.BooleanField(default=True),
        ),
    ]
