# Generated by Django 4.2.23 on 2025-06-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0013_activeproject_activeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='template', serialize=False, to='turkle.project')),
                ('html_template', models.TextField()),
            ],
        ),
    ]
