# Generated by Django 4.2.23 on 2025-06-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0013_activeproject_activeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='allotted_assignment_time',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='assignments_per_task',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Assignments per Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allotted_assignment_time',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='assignments_per_task',
            field=models.IntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
