# Generated by Django 4.2.23 on 2025-06-21 15:22

from django.db import migrations


def move_template_data(apps, schema_editor):
    Project = apps.get_model('turkle', 'Project')
    ProjectTemplate = apps.get_model('turkle', 'ProjectTemplate')
    db_alias = schema_editor.connection.alias

    for project in Project.objects.using(db_alias).all():
        if project.html_template:
            ProjectTemplate.objects.using(db_alias).create(
                project=project,
                html_template=project.html_template
            )


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0014_add_projecttemplate'),
    ]

    operations = [
        migrations.RunPython(move_template_data),
    ]
