# Generated by Django 4.2.23 on 2025-06-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turkle', '0015_move_project_html_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='html_template',
        ),
    ]
