name: "Docs Check"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install 'sphinx==7.1.2' --force-reinstall"
        docs-folder: "docs/"
